services:
  web:
    build:
      context: ..                  # ga één level omhoog naar je workspace-root
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace/apps/web
    volumes:
      - ../apps/web:/workspace/apps/web:cached
      - ../packages/ui:/workspace/packages/ui:cached
      - ..:/workspace:cached
    command: bash -lc "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mailpit

  db:
    image: postgres:17.5
    environment:
      POSTGRES_PASSWORD: supa123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  default:
    name: etenbijelshof-net
