name: CI & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-build:
    name: Lint, Format Check & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Format check with Prettier
        run: npx prettier --check .

      - name: Build with OpenNext
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: open-next-build
          path: .open-next

  deploy:
    name: Deploy to Cloudflare Workers
    needs: lint-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
